# Generated by Django 5.2.3 on 2025-07-21 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["email"],
                "permissions": [
                    ("can_block_user", "Can block user"),
                    ("can_mailinglist_cancel", "Can mailinglist cancel"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
