# Generated by Django 5.2.3 on 2025-07-20 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailinglist",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailinglist_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="mailing_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailings.mailinglist", verbose_name="Рассылка"
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailings.message", verbose_name="Сообщение"
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="mailinglist",
            name="recipients",
            field=models.ManyToManyField(to="mailings.recipient", verbose_name="Получатели"),
        ),
    ]
